spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 119.91.253.133:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yaml   #nacos配置文件后缀，下文配置发布的时候会用到。注意是yaml，不是yml
        #        group: sustech-store  #配置分组，默认分组是DEFAULT_GROUP
        refresh-enabled: true
        shared-configs:
          - data-id: common-database.yaml
            group: DEFAULT_GROUP
            refresh: true
          - data-id: commons.yaml
            group: DEFAULT_GROUP # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
            refresh: true # 是否自动刷新配置，默认为 false
